[pytest]
testpaths = test_cases
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -vs --alluredir=./temps --clean-alluredir
; allure generate -o report -c temps

# 注册自定义标记（markers）
markers =
    smoke: 冒烟测试（只测试核心流程）
    slow: 慢速测试
    full_flow: 完整流程测试
